@echo off
setlocal

set "SD=%~dp0"
set "TF=%TEMP%\gjf_calc_%RANDOM%.ps1"

echo $inputDir = '%SD%0' > "%TF%"
echo $outputDir = '%SD%' >> "%TF%"
echo $pairGroups = @{ >> "%TF%"
echo     CC = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo     CO = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo     CH = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo     OO = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo     OH = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo     HH = [System.Collections.Generic.List[double]]::new() >> "%TF%"
echo } >> "%TF%"
echo $globalMins = @{CC = [double]::MaxValue; CO = [double]::MaxValue; CH = [double]::MaxValue; OO = [double]::MaxValue; OH = [double]::MaxValue; HH = [double]::MaxValue} >> "%TF%"
echo $globalMinFiles = @{} >> "%TF%"
echo $total = (Get-ChildItem -Path $inputDir -Filter '*.gjf').Count >> "%TF%"
echo $count = 0 >> "%TF%"
echo Get-ChildItem -Path $inputDir -Filter '*.gjf' ^| Sort-Object Name ^| ForEach-Object { >> "%TF%"
echo     $count++ >> "%TF%"
echo     Write-Progress -Activity "Processing gjf files" -Status "$count / $total" -PercentComplete ($count * 100 / $total) >> "%TF%"
echo     $lines = Get-Content $_.FullName >> "%TF%"
echo     $atoms = [System.Collections.Generic.List[hashtable]]::new() >> "%TF%"
echo     foreach ($line in $lines) { >> "%TF%"
echo         $trimmed = $line.Trim() >> "%TF%"
echo         if ($trimmed -match '^^([CHO])\s+(-?\d+\.?\d*)\s+(-?\d+\.?\d*)\s+(-?\d+\.?\d*)$') { >> "%TF%"
echo             $atoms.Add(@{Type = $Matches[1]; X = [double]$Matches[2]; Y = [double]$Matches[3]; Z = [double]$Matches[4]}) ^| Out-Null >> "%TF%"
echo         } >> "%TF%"
echo     } >> "%TF%"
echo     $max = [double]::MaxValue >> "%TF%"
echo     $mins = @{CC = $max; CO = $max; CH = $max; OO = $max; OH = $max; HH = $max} >> "%TF%"
echo     $n = $atoms.Count >> "%TF%"
echo     for ($i = 0; $i -lt $n; $i++) { >> "%TF%"
echo         $a = $atoms[$i] >> "%TF%"
echo         for ($j = $i + 1; $j -lt $n; $j++) { >> "%TF%"
echo             $b = $atoms[$j] >> "%TF%"
echo             $dx = $a.X - $b.X >> "%TF%"
echo             $dy = $a.Y - $b.Y >> "%TF%"
echo             $dz = $a.Z - $b.Z >> "%TF%"
echo             $dist = [Math]::Sqrt($dx*$dx + $dy*$dy + $dz*$dz) >> "%TF%"
echo             $types = @($a.Type, $b.Type) ^| Sort-Object >> "%TF%"
echo             $key = $types -join '' >> "%TF%"
echo             if ($key -eq 'HO') { $key = 'OH' } >> "%TF%"
echo             if ($dist -lt $mins[$key]) { $mins[$key] = $dist } >> "%TF%"
echo         } >> "%TF%"
echo     } >> "%TF%"
echo     foreach ($k in @('CC','CO','CH','OO','OH','HH')) { >> "%TF%"
echo         if ($mins[$k] -lt $max) { >> "%TF%"
echo             $pairGroups[$k].Add($mins[$k]) >> "%TF%"
echo             if ($mins[$k] -lt $globalMins[$k]) { >> "%TF%"
echo                 $globalMins[$k] = $mins[$k] >> "%TF%"
echo                 $globalMinFiles[$k] = $_.Name >> "%TF%"
echo             } >> "%TF%"
echo         } >> "%TF%"
echo     } >> "%TF%"
echo } >> "%TF%"
echo $keys = @('CC','CO','CH','OO','OH','HH') >> "%TF%"
echo foreach ($k in $keys) { >> "%TF%"
echo     $outPath = Join-Path $outputDir "$k.txt" >> "%TF%"
echo     if ($pairGroups[$k].Count -gt 0) { >> "%TF%"
echo         [System.IO.File]::WriteAllLines($outPath, $pairGroups[$k].ToArray()) >> "%TF%"
echo     } else { >> "%TF%"
echo         Set-Content -Path $outPath -Value $null >> "%TF%"
echo     } >> "%TF%"
echo     Write-Host "$k.txt : $($pairGroups[$k].Count) values" >> "%TF%"
echo } >> "%TF%"
echo $summaryPath = Join-Path $outputDir "minimum_summary.txt" >> "%TF%"
echo $summaryLines = [System.Collections.Generic.List[string]]::new() >> "%TF%"
echo foreach ($k in @('CC','CO','CH','OO','OH','HH')) { >> "%TF%"
echo     if ($globalMinFiles.ContainsKey($k) -and $globalMinFiles[$k]) { >> "%TF%"
echo         $summaryLines.Add("$k  $($globalMins[$k])  $($globalMinFiles[$k])") >> "%TF%"
echo     } else { >> "%TF%"
echo         $summaryLines.Add("$k  N/A") >> "%TF%"
echo     } >> "%TF%"
echo } >> "%TF%"
echo [System.IO.File]::WriteAllLines($summaryPath, $summaryLines) >> "%TF%"
echo Write-Host 'Minimum summary saved to minimum_summary.txt' >> "%TF%"
echo Write-Host 'Done.' >> "%TF%"

powershell -ExecutionPolicy Bypass -File "%TF%"
del "%TF%"

echo.
echo All done. Output files: CC.txt CO.txt CH.txt OO.txt OH.txt HH.txt minimum_summary.txt
endlocal
